# Generated by Django 4.1.4 on 2023-01-05 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_pooler_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=10, verbose_name='Registration Number')),
                ('description', models.TextField(max_length=300, null=True, verbose_name='Description')),
                ('image', models.FileField(max_length=300, upload_to='Vehicle')),
                ('capacity', models.IntegerField(verbose_name='Passanger Capacity')),
                ('luggage_capacity', models.IntegerField(verbose_name='Luggage Capacity')),
                ('air_condition', models.BooleanField(default=False, verbose_name='A/C Status')),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pooler.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pooler')),
            ],
        ),
    ]
