# Generated by Django 4.1.4 on 2023-01-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='reg_no',
            field=models.CharField(max_length=20, verbose_name='Registration Number'),
        ),
    ]
