# Generated by Django 4.1.4 on 2023-01-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0004_ride_waypoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
