# Generated by Django 4.1.4 on 2023-01-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0005_ride_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waypoint',
            name='expected_time',
        ),
    ]
