# Generated by Django 4.1.4 on 2023-01-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0006_remove_waypoint_expected_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
