# Generated by Django 4.1.4 on 2023-01-28 04:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0007_ride_is_completed_alter_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='estimated_reaching_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 10, 6, 41, 158846)),
        ),
        migrations.AddField(
            model_name='ride',
            name='gender_preference',
            field=models.IntegerField(choices=[(0, 'Male Only'), (1, 'Female Only'), (2, 'No Preference')], default=2),
        ),
    ]
