# Generated by Django 4.1.4 on 2023-01-30 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0008_ride_estimated_reaching_time_ride_gender_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.IntegerField(default=4, editable=False, verbose_name='Passanger Capacity'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='estimated_reaching_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 16, 13, 39, 759253)),
        ),
    ]
