# Generated by Django 4.1.4 on 2023-01-30 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0009_alter_car_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='capacity',
            field=models.IntegerField(default=3, editable=False, verbose_name='Passanger Capacity'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='estimated_reaching_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 16, 15, 13, 940529)),
        ),
    ]
