# Generated by Django 4.1.4 on 2023-01-31 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0010_alter_car_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='estimated_reaching_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 31, 14, 8, 30, 560320)),
        ),
    ]
