# Generated by Django 4.1.4 on 2023-02-03 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0013_alter_ride_estimated_reaching_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='estimated_reaching_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 3, 11, 48, 43, 637467)),
        ),
    ]
