# Generated by Django 4.1.4 on 2023-02-10 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooler', '0014_alter_ride_estimated_reaching_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='estimated_reaching_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 14, 50, 58, 674561)),
        ),
    ]
