# Generated by Django 4.1.4 on 2023-04-27 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pooler", "0015_alter_ride_estimated_reaching_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="estimated_reaching_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 27, 17, 48, 49, 219120)
            ),
        ),
    ]
