# Generated by Django 4.1.4 on 2023-01-04 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='id_type',
            field=models.IntegerField(choices=[(0, 'Aadhar'), (1, 'Election ID'), (2, 'Pan Card'), (3, 'License')]),
        ),
        migrations.CreateModel(
            name='Pooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.ImageField(upload_to='', verbose_name='License')),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip_code', models.IntegerField(verbose_name='Zip Code')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
