# Generated by Django 4.1.4 on 2023-01-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userextra_id_type_pooler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooler',
            name='license',
            field=models.ImageField(upload_to='License', verbose_name='License'),
        ),
    ]
