# Generated by Django 4.1.4 on 2023-04-27 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_pooler_license"),
        ("administrator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercomplaint",
            name="pooler",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.pooler",
            ),
        ),
    ]
