# Generated by Django 4.1.4 on 2023-02-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seat',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
