# Generated by Django 4.1.4 on 2023-02-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_booking_destination_booking_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.CharField(default='', max_length=10),
        ),
    ]
